Repository boostcampwm-2021/iOS04-OwnMyWay, pull requests merged in 2021-12, with the labels that each got.

#222 ViewModel 단위테스트를 진행했습니다
  OwnMyWay/.swiftlint.yml
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay.xcodeproj/xcshareddata/xcschemes/OwnMyWay.xcscheme
  OwnMyWay/UsecaseTest/AddRecordUsecaseTest.swift
  OwnMyWay/ViewModelTest/AddLandmarkViewModelTest.swift
  OwnMyWay/ViewModelTest/AddRecordViewModelTest.swift
  OwnMyWay/ViewModelTest/DetailRecordViewModelTest.swift
  OwnMyWay/ViewModelTest/EnterDateViewModelTest.swift
  OwnMyWay/ViewModelTest/EnterTitleViewModelTest.swift
  OwnMyWay/ViewModelTest/HomeViewModelTest.swift
  OwnMyWay/ViewModelTest/LandmarkCartViewModelTest.swift
  OwnMyWay/ViewModelTest/ReservedTravelViewModelTest.swift
  OwnMyWay/ViewModelTest/SearchLandmarkViewModelTest.swift
  OwnMyWay/ViewModelTest/StartedTravelViewModelTest.swift
Labels: test

#223 상세 기록 화면에서 현재 보고 있는 사진을 공유하게 수정했습니다.
  OwnMyWay/OwnMyWay/Presentation/DetailRecordScene/View/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/Presentation/Utils/Extension/UIView+.swift
Labels: refactor

#228 위치 권한과 관련된 오류 및 개선점 반영
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Data/Repositories/CoreDataTravelRepository.swift
  OwnMyWay/OwnMyWay/Domain/Interfaces/Repositories/TravelRepository.swift
  OwnMyWay/OwnMyWay/Domain/Usecases/DefaultStartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Infrastructure/Location/LocationManager.swift
  OwnMyWay/OwnMyWay/Presentation/AddLanmarkScene/View/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/Presentation/AddRecordScene/View/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/Presentation/CompleteScene/CompleteCreation/View/CompleteCreationViewController.swift
  OwnMyWay/OwnMyWay/Presentation/CompleteScene/CompleteEditing/View/CompleteEditingViewController.swift
  OwnMyWay/OwnMyWay/Presentation/DetailImageScene/View/DetailImageViewController.swift
  OwnMyWay/OwnMyWay/Presentation/DetailRecordScene/View/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/Presentation/EnterDateScene/View/EnterDateViewController.swift
  OwnMyWay/OwnMyWay/Presentation/EnterTitleScene/View/EnterTitleViewController.swift
  OwnMyWay/OwnMyWay/Presentation/SearchLandmarkScene/View/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/ReservedTravel/View/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/StartedTravel/Interface/Usecase/StartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/StartedTravel/OngoingTravel/View/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/StartedTravel/OngoingTravel/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/StartedTravel/OutdatedTravel/View/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/Presentation/TravelScene/StartedTravel/StartedTravelViewModel.swift
  OwnMyWay/OwnMyWay/Resource/Info.plist
  OwnMyWay/ViewModelTest/StartedTravelViewModelTest.swift
Labels: bugfix, refactor
