Repository boostcampwm-2021/iOS04-OwnMyWay, pull requests merged in 2021-11, with the labels that each got.

#29 코어데이터 기초 작업
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
Labels: feature

#30 여행 추가 화면 Usecase, ViewModel 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Usecase/CreateTravelUsecase.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
Labels: feature

#31 Plus 카드 Custom Cell 구현
  .gitattributes
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/View/PlusCell.swift
  OwnMyWay/OwnMyWay/View/PlusCell.xib
Labels: feature

#32 코어데이터 Record, Landmark 생성 추가
  OwnMyWay/.swiftlint.yml
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
Labels: feature

#33 CreateViewScene 생성 및 타이틀 텍스트필드 추가
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Main.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ViewController.swift
Labels: feature

#34 관광명소 카트 기초 세팅
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Usecase/LandmarkCartUsecase.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
Labels: feature

#35 SearchLandmark 화면 구성
  OwnMyWay/.swiftlint.yml
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/landmark.dataset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/landmark.dataset/landmark.json
  OwnMyWay/OwnMyWay/Model/LandmarkDTO.swift
  OwnMyWay/OwnMyWay/Repository/LandmarkDTORepository.swift
  OwnMyWay/OwnMyWay/Usecase/CreateTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/SearchLandmarkUsecase.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: feature

#38 AddLandmark Scene 생성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
Labels: feature

#39 Instantiable, Coordinator 추가
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator.swift
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/SceneDelegate.swift
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/Instantiable.swift
Labels: feature, style

#40 AddLandmark Scene 구현ing, LandmarkCart Scene 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.xib
  OwnMyWay/OwnMyWay/View/PlusCell.xib
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
Labels: feature, refactor

#42 여행 생성화면에 캘린더 추가
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/IdentityBlue.colorset/Contents.json
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
Labels: feature, refactor

#43 mapkit 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/LandmarkPin.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/LandmarkPin.imageset/landmarkPin.png
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
Labels: feature

#48 당일치기 여행 불가능한 버그 수정
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
Labels: bugfix

#49 Mapkit 최종 완성 - 시작위치, 팝업 화면 수정, 프로토콜로 함수 분리
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/MapAvailable.swift
Labels: feature

#50 CoreData 리팩토링
  OwnMyWay/.swiftlint.yml
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Model/Landmark.swift
  OwnMyWay/OwnMyWay/Model/LandmarkDTO.swift
  OwnMyWay/OwnMyWay/Model/LandmarkMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/LandmarkMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/Model/Record.swift
  OwnMyWay/OwnMyWay/Model/RecordMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/RecordMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/CreateTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
Labels: bugfix, refactor, style

#51 Travel 객체 전달 및 Landmark 추가 기능 구현
  OwnMyWay/OwnMyWay/Coordinator.swift
  OwnMyWay/OwnMyWay/Usecase/LandmarkCartUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
Labels: feature, refactor

#52 다음버튼 추가 및 명소 추가화면 다양한 기기 대응
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/View/NextButton.swift
  OwnMyWay/OwnMyWay/View/NextButton.xib
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
Labels: feature

#53 SearchLandmark 화면 생성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/SearchLandmark.storyboard
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: feature

#55 SearchLandmark 구현 완료
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator.swift
  OwnMyWay/OwnMyWay/Model/LandmarkDTO.swift
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: feature

#75 예정된 여행 화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator.swift
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/ReservedTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/ReservedTravelUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
Labels: feature

#76 Home 화면 일부 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/100.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/1024.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/114.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/120.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/144.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/152.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/167.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/180.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/20.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/29.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/40.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/50.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/57.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/58.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/60.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/72.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/76.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/80.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/87.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/airplane.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/airplane.imageset/airplane.jpeg
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/Usecase/HomeUsecase.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.xib
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.swift
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.xib
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
Labels: feature

#79 Landmark RelationShip fetch 문제 해결
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/SearchLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/TravelUpdatable.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
Labels: feature, bugfix

#80 예정된 여행 삭제 기능 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/TravelFetchable.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
Labels: P3, feature

#82 새로운 여행을 만드는 과정에서 CoreData에 Travel을 등록하는 시점 조정
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/LandmarkCartCoordinator.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/CreateTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/LandmarkCartUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
Labels: bugfix

#84 코드 컨벤션 리팩토링
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CreateTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/HomeCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/LandmarkCartCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/SearchLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Repository/LandmarkDTORepository.swift
  OwnMyWay/OwnMyWay/Repository/LandmarkRepository.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/CreateTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/HomeUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/ReservedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/SearchLandmarkUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/MapAvailable.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/TravelUpdatable.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: refactor, style

#85 CompleteCreation 화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CompleteCreationCoordinator.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CompleteCreation.storyboard
  OwnMyWay/OwnMyWay/Usecase/CompleteCreationUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/NextButton.xib
  OwnMyWay/OwnMyWay/View/PlusCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteCreationViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteCreationViewModel.swift
Labels: feature

#86 HomeLayout 제대로 표시되지 않던 문제 해결
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/UIImageView+.swift
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/PlusCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.xib
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
Labels: bugfix

#88 mapView 관광명소 전부 다 안보이는 문제 해결
  OwnMyWay/OwnMyWay/ViewController/MapAvailable.swift
Labels: bugfix

#87 reservedTravel 화면 완성
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/ReservedTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/ReservedTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.xib
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
Labels: feature

#90 Ongoing Skeleton 작성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/OngoingCoordinator.swift
  OwnMyWay/OwnMyWay/Storyboard/Ongoing.storyboard
  OwnMyWay/OwnMyWay/Usecase/OngoingUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingViewModel.swift.swift
Labels: feature

#91 ongoing 화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/HomeCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Model/Record.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CompleteCreation.storyboard
  OwnMyWay/OwnMyWay/Storyboard/DetailRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OutdatedTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/SearchLandmark.storyboard
  OwnMyWay/OwnMyWay/Usecase/AddRecordUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/DetailRecordUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/OngoingTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/OutdatedTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/DateHeaderView.swift
  OwnMyWay/OwnMyWay/View/DateHeaderView.xib
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/MapCell.xib
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.xib
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OutdatedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
  OwnMyWay/OwnMyWayTests/OwnMyWayTests.swift
Labels: feature

#93 CoreData ~ Repository
  OwnMyWay/.swiftlint.yml
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Model/Location.swift
  OwnMyWay/OwnMyWay/Model/LocationMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/LocationMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
Labels: feature

#95 BackButton 클릭시 홈화면 Fetch 기능 구현
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OutdatedTravelViewModel.swift
Labels: bugfix

#96 사용자 경로추적 구현 완료
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/OngoingTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/MapCell.xib
  OwnMyWay/OwnMyWay/ViewController/MapAvailable.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
Labels: feature

#122 다크모드 대응 및 버튼 디자인 통일
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CompleteCreation.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/ReservedTravel.storyboard
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteCreationViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
Labels: design

#123 CoreData 재구성, Add Record 화면 스켈레톤 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CreateTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/HomeCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/SearchLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Model/LandmarkMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/LandmarkMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/Model/LocationMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/LocationMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/Model/Record.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataClass.swift
  OwnMyWay/OwnMyWay/Model/TravelMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/View/RecordAnnotationView.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.xib
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/RecordMO+CoreDataClass.swift
  OwnMyWay/RecordMO+CoreDataProperties.swift
Labels: feature, refactor

#124 Ongoing 화면 MapView UserLocation Tracking 기능 개선
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/MapCell.xib
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LocationManager.swift
  OwnMyWay/OwnMyWay/ViewController/MapAvailable.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
Labels: feature

#125 모든 VC의 메모리 누수 문제 해결
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
Labels: bugfix

#126 Navigation 방식 수정
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
Labels: refactor, style

#128 상세화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CompleteCreationCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/LandmarkCartCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/DetailRecord.storyboard
  OwnMyWay/OwnMyWay/Usecase/DetailRecordUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/OngoingTravelUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/RecordUpdatable.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
Labels: feature

#129 Keyboard에 따른 화면 높이 전환 구현
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
Labels: feature

#130 DetailRecord 화면에서 폴라로이드 형식의 뷰를 구성해 공유하는 기능 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
Labels: feature

#131 Ongoing map Icon Button 색깔 및 위치 변경
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/MapCell.xib
Labels: feature

#132 AddRecord 화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/BundleImage/addImage.png
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/AddRecordUsecase.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.xib
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ImageFileManager.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
Labels: feature

#133 Outdated화면 완성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/Storyboard/OutdatedTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/StartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/OutdatedMapCell.swift
  OwnMyWay/OwnMyWay/View/OutdatedMapCell.xib
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OutdatedTravelViewModel.swift
Labels: feature

#134 addRecord 이슈 수정
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.xib
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ImageFileManager.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: bugfix

#135 각 여행 수정/삭제 구현, 새로운 여행 화면 디자인 개선, 수정완료 화면 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CompleteEditingCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CreateTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/HomeCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Model/Location.swift
  OwnMyWay/OwnMyWay/Model/Travel.swift
  OwnMyWay/OwnMyWay/Storyboard/CompleteEditing.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Usecase/CompleteEditingUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/StartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteEditingViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/TravelEditableViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteEditingViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OutdatedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
Labels: feature, design

#138 Location Search 기능 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/SearchLocationCoordinator.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/SearchLocation.storyboard
  OwnMyWay/OwnMyWay/View/LocationTableViewCell.swift
  OwnMyWay/OwnMyWay/View/LocationTableViewCell.xib
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLocationViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLocationViewModel.swift
Labels: feature

#139 Feat/delete photo
  OwnMyWay/OwnMyWay/Usecase/AddRecordUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ImageFileManager.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: feature

#141 Location 오류 해결, AddRecord 리펙토링
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Usecase/AddRecordUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: feature, bugfix, refactor

#165 이미지가 까맣게 나오는 문제를 수정하였습니다.
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
Labels: bugfix

#167 LandmarkCart UI 재구성
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/LandmarkCartCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Storyboard/AddLandmark.storyboard
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/Storyboard/ReservedTravel.storyboard
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LandmarkCartViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/LandmarkCartViewModel.swift
Labels: feature

#168 AddRecord, RecordDetail 화면 디자인 및 기능 수정
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/IdentityBlue.colorset/Contents.json
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/DetailRecord.storyboard
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
Labels: feature, design

#169 홈 화면 디자인 및 여행 추가 버튼 생성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/AddButton.imageset/AddButton-1x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AddButton.imageset/AddButton-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AddButton.imageset/AddButton-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AddButton.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/HomeBackground.colorset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/HomeContent.colorset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/MainIcon.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/MainIcon.imageset/mainIcon.svg
  OwnMyWay/OwnMyWay/Assets.xcassets/Setting.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Setting.imageset/setting-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Setting.imageset/setting-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Setting.imageset/setting.png
  OwnMyWay/OwnMyWay/BundleFont/DancingScript-Bold.ttf
  OwnMyWay/OwnMyWay/BundleFont/DancingScript-Regular.ttf
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/View/CommentCell.xib
  OwnMyWay/OwnMyWay/View/HomeBackgroundView.swift
  OwnMyWay/OwnMyWay/View/HomeBackgroundView.xib
  OwnMyWay/OwnMyWay/View/TravelCardCell.xib
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.xib
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
Labels: feature, design

#170 Ongoing화면 UI 개선
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/IdentityBlue.colorset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Setting.imageset/Contents.json
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Extension/UIButton+.swift
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CompleteCreation.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CompleteEditing.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/DetailRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/LandmarkCart.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/View/MapCell.swift
  OwnMyWay/OwnMyWay/View/MapCell.xib
  OwnMyWay/OwnMyWay/View/OMWMapView.swift
  OwnMyWay/OwnMyWay/View/OMWSegmentedControl.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
Labels: feature, design

#171 SegmentedControl 제대로 표시 안되던 버그 수정
  OwnMyWay/OwnMyWay/View/OMWSegmentedControl.swift
Labels: bugfix

#172 Outdated 화면 UI 재구성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OutdatedTravel.storyboard
  OwnMyWay/OwnMyWay/View/OMWMapView.swift
  OwnMyWay/OwnMyWay/View/OutdatedMapCell.swift
  OwnMyWay/OwnMyWay/View/OutdatedMapCell.xib
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
Labels: feature, design

#173 PlusCard 디자인 변경
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/PlusCard.colorset/Contents.json
  OwnMyWay/OwnMyWay/View/PlusCell.swift
  OwnMyWay/OwnMyWay/View/PlusCell.xib
Labels: design

#174 여행 제목 입력과 날짜 입력화면 분리
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/AddLandmarkCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CreateTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/EnterDateCoordinator.swift
  OwnMyWay/OwnMyWay/Storyboard/CompleteEditing.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/EnterDate.storyboard
  OwnMyWay/OwnMyWay/Usecase/EnterDateUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/EnterDateViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/EnterDateViewModel.swift
Labels: design

#176 홈 화면 디자인 완성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-1x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Unfold.imageset/Contents.json
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/View/MessageCell.swift
  OwnMyWay/OwnMyWay/View/MessageCell.xib
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.xib
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
Labels: design

#178 NavigationController 디자인 변경
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/SceneDelegate.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteCreationViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteEditingViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/EnterDateViewController.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CreateTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/EnterDateViewModel.swift
Labels: design

#177 Error Handler 구현
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Extension/UIViewController+.swift
  OwnMyWay/OwnMyWay/Repository/LandmarkRepository.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/CompleteCreationUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/CompleteEditingUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/DetailRecordUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/HomeUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/OutdatedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/ReservedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/SearchLandmarkUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/StartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/ViewController/AddLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteCreationViewController.swift
  OwnMyWay/OwnMyWay/ViewController/CompleteEditingViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ErrorManager.swift
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewController/LocationManager.swift
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/OutdatedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ReservedTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/SearchLandmarkViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddLandmarkViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteCreationViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteEditingViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OutdatedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: feature

#181 fix: 위치 트래킹 미종료 버그 해결
  OwnMyWay/OwnMyWay/ViewController/OngoingTravelViewController.swift
Labels: bugfix

#182 ImagePicker 적용 및 사진 수 제한
  OwnMyWay/OwnMyWay/SceneDelegate.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: feature

#183 맵 핀 고화질 설정
  OwnMyWay/OwnMyWay/Assets.xcassets/LandmarkPin.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/LandmarkPin.imageset/LandmarkPin.png
  OwnMyWay/OwnMyWay/Assets.xcassets/LandmarkPin.imageset/landmarkPin.png
  OwnMyWay/OwnMyWay/Assets.xcassets/RecordPin.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/RecordPin.imageset/RecordPin.png
  OwnMyWay/OwnMyWay/Assets.xcassets/RecordPin.imageset/RecordPin.svg
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/View/RecordAnnotationView.swift
Labels: design

#184 앱 아이콘 수정
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/100.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/1024.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/114.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/120.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/144.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/152.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/167.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/180.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/20.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/29.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/40.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/50.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/57.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/58.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/60.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/72.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/76.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/80.png
  OwnMyWay/OwnMyWay/Assets.xcassets/AppIcon.appiconset/87.png
Labels: design

#185 사진 비동기 호출 및 순서 맞게 변경
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: bugfix

#186 Repository UIKit 의존성 제거 & JSON 파일 개선
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/AppDelegate.swift
  OwnMyWay/OwnMyWay/Assets.xcassets/landmark.dataset/Contents.json
  OwnMyWay/OwnMyWay/BundleJSON/landmark.json
  OwnMyWay/OwnMyWay/Coordinator/AddRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CompleteCreationCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/CompleteEditingCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/HomeCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OngoingTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/OutdatedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/ReservedTravelCoordinator.swift
  OwnMyWay/OwnMyWay/Repository/LandmarkRepository.swift
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.xib
  OwnMyWay/OwnMyWay/ViewController/LocationManager.swift
Labels: refactor, design

#187 voiceOver를 통한 접근성 개선
  OwnMyWay/OwnMyWay/Storyboard/AddRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/CreateTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/DetailImage.storyboard
  OwnMyWay/OwnMyWay/Storyboard/DetailRecord.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/View/DateHeaderView.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/OMWMapView.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
Labels: feature

#190 CoreData Repository 비동기 개선
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/CompleteCreationUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/CompleteEditingUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/DetailRecordUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/HomeUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/ReservedTravelUsecase.swift
  OwnMyWay/OwnMyWay/Usecase/StartedTravelUsecase.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/LocationManager.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteCreationViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/CompleteEditingViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/OngoingTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/ReservedTravelViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/SearchLandmarkViewModel.swift
Labels: refactor

#191 홈 화면 UI 개선 및 메시지 닫기 기능 추가
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OngoingTravel.storyboard
  OwnMyWay/OwnMyWay/Storyboard/OutdatedTravel.storyboard
  OwnMyWay/OwnMyWay/View/MessageCell.swift
  OwnMyWay/OwnMyWay/View/MessageCell.xib
  OwnMyWay/OwnMyWay/View/TravelSectionHeader.xib
  OwnMyWay/OwnMyWay/ViewController/HomeViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/HomeViewModel.swift
Labels: feature, design

#192 Kingfisher 의존성을 제거하고 이미지 저장방식을 상대경로로 저장하게 수정했습니다.
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Coordinator/DetailImageCoordinator.swift
  OwnMyWay/OwnMyWay/Coordinator/DetailRecordCoordinator.swift
  OwnMyWay/OwnMyWay/Extension/UIImageView+.swift
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/Model/Record.swift
  OwnMyWay/OwnMyWay/Model/RecordMO+CoreDataProperties.swift
  OwnMyWay/OwnMyWay/OwnMyWay.xcdatamodeld/OwnMyWay.xcdatamodel/contents
  OwnMyWay/OwnMyWay/Repository/TravelRepository.swift
  OwnMyWay/OwnMyWay/Usecase/AddRecordUsecase.swift
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/PhotoCell.swift
  OwnMyWay/OwnMyWay/View/RecordAnnotationView.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.swift
  OwnMyWay/OwnMyWay/View/RecordCardCell.xib
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailImageViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/ImageFileManager.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailImageViewModel.swift
  OwnMyWay/OwnMyWay/ViewModel/DetailRecordViewModel.swift
  OwnMyWay/RecordMO+CoreDataClass.swift
Labels: bugfix, refactor

#194 런치스크린 추가
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AddButton.imageset/AddButton-1x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AddButton.imageset/AddButton-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AddButton.imageset/AddButton-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AddButton.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AppName.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/AppName.imageset/OwnMyWay.svg
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-1x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Fold.imageset/fold-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/LandmarkPin.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/LandmarkPin.imageset/LandmarkPin.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/MainIcon.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/MainIcon.imageset/mainIcon.svg
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/RecordPin.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/RecordPin.imageset/RecordPin.svg
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Setting.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Setting.imageset/setting-2x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Setting.imageset/setting-3x.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Setting.imageset/setting.png
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/Unfold.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/airplane.imageset/Contents.json
  OwnMyWay/OwnMyWay/Assets.xcassets/Image/airplane.imageset/airplane.jpeg
  OwnMyWay/OwnMyWay/Storyboard/Base.lproj/LaunchScreen.storyboard
Labels: feature

#196 ImageCache 작업과 prepareForReuse() 를 손봤습니다.
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Extension/UIImageView+.swift
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/Extension/URLSessionDataTask+.swift
  OwnMyWay/OwnMyWay/View/LandmarkCardCell.swift
  OwnMyWay/OwnMyWay/View/OMWCollectionViewCell.swift
  OwnMyWay/OwnMyWay/View/TravelCardCell.swift
  OwnMyWay/OwnMyWay/ViewController/ImageFileManager.swift
Labels: refactor

#197 FSCalendar 작별 작업 (커스텀 캘린더 구현)
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Assets.xcassets/Color/WJGreen.colorset/Contents.json
  OwnMyWay/OwnMyWay/Extension/Date+.swift
  OwnMyWay/OwnMyWay/Storyboard/EnterDate.storyboard
  OwnMyWay/OwnMyWay/View/CalendarCell.swift
  OwnMyWay/OwnMyWay/View/CalendarCell.xib
  OwnMyWay/OwnMyWay/View/OMWCalendar.swift
  OwnMyWay/OwnMyWay/ViewController/CalendarDataSource.swift
  OwnMyWay/OwnMyWay/ViewController/CreateTravelViewController.swift
  OwnMyWay/OwnMyWay/ViewController/EnterDateViewController.swift
Labels: feature, refactor, design

#199 이미지의 순서를 보장하고 이미지 줌 뷰에서의 사용성을 개선했습니다.
  OwnMyWay/OwnMyWay/Extension/UIView+.swift
  OwnMyWay/OwnMyWay/Storyboard/DetailImage.storyboard
  OwnMyWay/OwnMyWay/View/LandmarkAnnotationView.swift
  OwnMyWay/OwnMyWay/ViewController/AddRecordViewController.swift
  OwnMyWay/OwnMyWay/ViewController/DetailImageViewController.swift
  OwnMyWay/OwnMyWay/ViewModel/AddRecordViewModel.swift
Labels: feature, bugfix, style, design

#204 13 버전에서 캘린더 다크모드 표시 못하던 문제와 가로모드를 잠궜습니다.
  OwnMyWay/OwnMyWay/AppDelegate.swift
  OwnMyWay/OwnMyWay/Info.plist
  OwnMyWay/OwnMyWay/View/OMWCalendar.swift
Labels: bugfix

#209 15미만 버전에서 홈화면이 제대로 그려지지 않던 문제를 해결했습니다.
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay/Presentation/Common/CollectionView/MessageCell.xib
  OwnMyWay/OwnMyWay/Presentation/Common/CollectionView/OMWCollectionViewCell.swift
  OwnMyWay/OwnMyWay/Presentation/Common/CollectionView/TravelCardCell.xib
  OwnMyWay/OwnMyWay/Presentation/Common/CollectionView/TravelSectionHeader.xib
  OwnMyWay/OwnMyWay/Presentation/HomeScene/View/Base.lproj/Home.storyboard
  OwnMyWay/OwnMyWay/Presentation/HomeScene/View/HomeViewController.swift
Labels: bugfix

#220 AddRecordUsecase 테스트 코드 작성
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay.xcodeproj/xcshareddata/xcschemes/OwnMyWay.xcscheme
  OwnMyWay/UsecaseTest/AddRecordUsecaseTest.swift
Labels: test

#221 테스트코드 충돌로 인한 Revert
  OwnMyWay/OwnMyWay.xcodeproj/project.pbxproj
  OwnMyWay/OwnMyWay.xcodeproj/xcshareddata/xcschemes/OwnMyWay.xcscheme
  OwnMyWay/UsecaseTest/AddRecordUsecaseTest.swift
Labels: bugfix
